name: Anchor Solana Integration Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  anchor-test:
    name: Build and test program
    runs-on: ubuntu-latest
    container: projectserum/build:v0.25.0
    steps:
      - uses: actions/checkout@v3
        name: Coppy files to container
      - run: npm install
        name: Install NPM dependencies
      - run: rustup default stable
        name: Set Rust compailer to stable
      - run: cargo test
        name: Program end to end tests
      - run: solana-keygen new --outfile test-wallet.json --no-bip39-passphrase
        name: Create test wallet
      - run: anchor test --provider.wallet test-wallet.json
        name: Build and integrate test program using test wallet
      - uses: actions/upload-artifact@v3
        name: Pack the built files
        with:
          name: programs
          path: target/deploy/*.so