name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  anchor-test:
    runs-on: ubuntu-latest
    container: projectserum/build:v0.25.0
    steps:
      - uses: actions/checkout@v3
      - run: anchor test